#!/bin/bash

echo "This script assumes that curl is installed"

HERE=`pwd`

mkdir -p ~/bin
ln -s ~/.emacs.d/dot.sbt ~/.sbt
ln -s ~/.emacs.d/dot.emacs ~/.emacs
ln -s ~/.emacs.d/dot.vimrc ~/.vimrc

# Ammonite Scala shell
mkdir ~/.ammonite
ln -s ~/.emacs.d/predef.scala ~/.ammonite/predef.scala

cd ~/bin

unzip $HERE/sbt-launcher.zip
cat > sbt <<EOF
#!/bin/bash
sbt-launcher/sbt %*
EOF
chmod 755 sbt

curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
chmod 755 boot

curl -fsSLo lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
chmod 755 lein

# Note: no 'latest' link in Maven's repo; have to upgrade this manually
curl -fsSLo maven-latest.tgz http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
tar -xzvf maven-latest.tgz
ln -s apache-maven* maven
cat > mvn <<EOF
#!/bin/bash
export MAVEN_HOME=`pwd`/maven
export M2_HOME=`pwd`/maven
`pwd`/maven/bin/mvn $*
EOF
chmod 755 mvn

# Ammonite Scala shell
curl -L -o ~/bin/amm https://git.io/vo4w5 && chmod +x ~/bin/amm

cat >> ~/.bashrc <<EOF

export PATH="$PATH:~/bin"
EOF


echo "See the 'baseline' folder for common apps"
