#!/bin/sh

# Start Desktop

# We'll use a custom startup script
#[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup

cd ~

# Homebrew and friends.  Brew-installed things should override apt-installed things
export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH

# Node version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -nowin &   # Enable clipboard integration
env -u SESSION_MANAGER -u DBUS_SESSION_BUS_ADDRESS dbus-launch --exit-with-session xfce4-session
