#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export FONT_DIR=~/.fonts
elif [[ "$OSTYPE" == "darwin"* ]]; then
    export FONT_DIR=~/Library/Fonts
fi

echo "Installing fonts into $FONT_DIR"


mkdir -p $FONT_DIR
mkdir f
cd f && unzip -o '../*.zip' && cd ..
find . | grep .ttf$ | xargs ./install_ttf
rm -fr f
