#!/usr/bin/env bash

DOCKER_DEV_DEVRC=~/.devrc
export DOCKER_DEV_CONFDIR="$DOCKER_DEV_DEVRC/conf"
export DOCKER_DEV_USERSTATE="$DOCKER_DEV_DEVRC/home"
export DOCKER_DEV_USERDOCS="$DOCKER_DEV_DEVRC/docs"

export DOCKER_DEV_USERBREW="$DOCKER_DEV_USERSTATE/linuxbrew"
export DOCKER_DEV_USERHOME="$DOCKER_DEV_USERSTATE/$USER"

export IMAGENAME=docker-devenv
export CONTAINERNAME=`whoami`
export HOSTNAME=dev

if command -v docker &>/dev/null; then
    export PODMAN='docker'
elif command -v podman &>/dev/null; then
    export PODMAN='podman'
else
    echo "Docker or Podman must be installed"
    exit 1
fi
